markdown: kramdown
permalink: /:categories/:title

production_url: http://kizu.ru/textyll/ # Could it be gussed and defaulted?
relative_permalinks: false

github_repo: "kizu/textyll" # Could it be gussed and defaulted?

link_handles:
    - prefix: "@"
      handle: "https://twitter.com/"
    - prefix: "gh:"
      handle: "https://github.com/"

## Unquote to set classes to quoted links instead of inline attributes
# quoted_link_wrapper_class: link link-wrapper
# quoted_link_inner_class: link-inner

langs:
    - ru
    - en

default_lang: en

loc:
    laquo:
        ru: "«"
        en: "“"
    raquo:
        ru: "»"
        en: "”"
