markdown: kramdown

permalink: /:categories/:title
relative_permalinks: false

## Production URL without ending slash
production_url: http://kizu.ru/textyll

github_repo: "kizu/textyll" # Could it be gussed and defaulted?

link_handles:
    - prefix: "@"
      handle: "https://twitter.com/"
    - prefix: "gh:"
      handle: "https://github.com/"

## Unquote to set classes to quoted links instead of inline attributes
# quoted_link_wrapper_class: link link-wrapper
# quoted_link_inner_class: link-inner


## Localization
langs:
    - ru
    - en

default_lang: en

loc:
    laquo:
        ru: "«"
        en: "“"
    raquo:
        ru: "»"
        en: "”"
